/**
 * Invoice Generated: success page after the server confirms generation. Both
 * wizard entries (Generate Invoice picker and the post-sale Review) end here.
 *
 * Gate (FINAL_LIST row 6): View Invoice renders only with invoice.view_own; no
 * other actions. The old Download button is dropped as an "other action";
 * downloading is on the invoice detail.
 */
import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import Svg, { Circle, Path } from 'react-native-svg';

import { adminColors, adminRadius, adminSpacing, adminType } from '../../../theme';
import { BillingButton, BillingFooter, BillingScreen, Card, InfoNote } from './BillingParts';
import type { WarehouseScreenBaseProps } from './types';

export interface InvoiceGeneratedScreenProps extends WarehouseScreenBaseProps {
  /** Invoice number assigned by the server. */
  invoiceId: string;
  onViewInvoice: (invoiceId: string) => void;
}

function SuccessIcon() {
  return (
    <Svg width={36} height={36} viewBox="0 0 24 24" fill="none">
      <Circle cx="12" cy="12" r="10" stroke={adminColors.success.text} strokeWidth="2.2" />
      <Path d="M8 12l3 3 5-6" stroke={adminColors.success.text} strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

function DocumentIcon() {
  return (
    <Svg width={20} height={20} viewBox="0 0 24 24" fill="none">
      <Path
        d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6z"
        stroke={adminColors.onBrand}
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <Path d="M14 2v6h6M16 13H8M16 17H8M10 9H8" stroke={adminColors.onBrand} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

export function InvoiceGeneratedScreen({ can, onBack, invoiceId, onViewInvoice }: InvoiceGeneratedScreenProps) {
  const canView = can('invoice.view_own');
  return (
    <BillingScreen
      title="Invoice Generated"
      onBack={onBack}
      footer={
        canView ? (
          <BillingFooter>
            <BillingButton label="View Invoice" icon={<DocumentIcon />} onPress={() => onViewInvoice(invoiceId)} />
          </BillingFooter>
        ) : null
      }
    >
      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        <View style={styles.iconCircle}>
          <SuccessIcon />
        </View>
        <Text style={styles.title}>Invoice Generated</Text>
        <Card>
          <Text style={styles.numberLabel}>Invoice Number</Text>
          <Text style={styles.numberValue}>{invoiceId}</Text>
        </Card>
        <InfoNote>
          This number is generated by the backend under a sequence/lock — never counted or assigned on the client.
        </InfoNote>
      </ScrollView>
    </BillingScreen>
  );
}

const ICON_CIRCLE = 80;

const styles = StyleSheet.create({
  scrollContent: { paddingHorizontal: adminSpacing.lg, paddingTop: adminSpacing.xxl, paddingBottom: adminSpacing.xl },
  iconCircle: {
    alignSelf: 'center',
    width: ICON_CIRCLE,
    height: ICON_CIRCLE,
    borderRadius: adminRadius.full,
    backgroundColor: adminColors.success.bg,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: adminSpacing.lg,
  },
  title: { ...adminType.title, color: adminColors.ink, textAlign: 'center', marginBottom: adminSpacing.lg },
  numberLabel: { ...adminType.rowMeta, color: adminColors.muted, textAlign: 'center' },
  numberValue: { ...adminType.kpiValue, color: adminColors.ink, textAlign: 'center', marginTop: adminSpacing.xs },
});
