/**
 * Invoice Detail: the read-only invoice with Download / Share.
 *
 * Gate (FINAL_LIST row 4): read-only; Download and Share render for
 * invoice.view_own. Generated By and the timeline render only when the record
 * carries them. Scope: a Sub scope only opens invoices of its own warehouse;
 * any other id shows "not found" (an empty result, never a 403-style "not
 * allowed", CLAUDE.md 2.1). The server enforces the same.
 *
 * Absorbs (pairs M9-S03, M9-S06):
 *   - Main InvoiceDetailScreen: same sections; its privacy note is ported for
 *     the Main view (scope.warehouseId undefined).
 *   - Main DownloadInvoiceScreen and Sub SubWarehouseInvoicePreviewScreen: the
 *     Download action here (with the "Invoice downloaded" toast from Preview);
 *     Main's signed-link note is ported for the Main view.
 *   - Sub SubWarehouseInvoiceHistoryDetailScreen: its Invoice Type, Generated
 *     By, Status and Download Availability fields are in Invoice Information.
 *     The Sub shell's history-detail and preview flows open this screen with
 *     the invoice id.
 */
// Design id: M9-S03
import React, { useEffect, useRef, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, View } from 'react-native';
import Svg, { Path } from 'react-native-svg';

import { adminColors, adminRadius, adminSpacing, adminType } from '../../../theme';
import {
  BillingButton,
  BillingFooter,
  BillingScreen,
  BillingToast,
  Card,
  DownloadIcon,
  HeaderIconButton,
  InfoCard,
  InfoNote,
  inScope,
  isAllWarehouses,
  PermissionNote,
  SectionTitle,
} from './BillingParts';
import { SAMPLE_INVOICE_DETAIL } from './fixtures';
import type { InvoiceDetailRecord, WarehouseScreenBaseProps } from './types';

export interface InvoiceDetailScreenProps extends WarehouseScreenBaseProps {
  invoiceId: string;
  /** Detail record; defaults to the mock invoice until the invoice API is wired. */
  invoice?: InvoiceDetailRecord | undefined;
  onDownload?: ((invoiceId: string) => void) | undefined;
  onShare?: ((invoiceId: string) => void) | undefined;
}

const TOAST_MS = 3000;

function TimelineCheckIcon() {
  return (
    <Svg width={18} height={18} viewBox="0 0 24 24" fill="none">
      <Path
        d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10zM9 12l2 2 4-4"
        stroke={adminColors.success.text}
        strokeWidth="2.4"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </Svg>
  );
}

export function InvoiceDetailScreen({
  scope,
  can,
  onBack,
  invoiceId,
  invoice = SAMPLE_INVOICE_DETAIL,
  onDownload,
  onShare,
}: InvoiceDetailScreenProps) {
  const [showToast, setShowToast] = useState(false);
  const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(
    () => () => {
      if (toastTimer.current) clearTimeout(toastTimer.current);
    },
    [],
  );

  const canView = can('invoice.view_own');
  const record: InvoiceDetailRecord = { ...invoice, invoiceId };

  if (!inScope(scope, record.warehouseId)) {
    return (
      <BillingScreen title="Invoice Detail" onBack={onBack}>
        <View style={styles.scrollContent}>
          <PermissionNote>Invoice {invoiceId} was not found.</PermissionNote>
        </View>
      </BillingScreen>
    );
  }

  const handleDownload = () => {
    setShowToast(true);
    if (toastTimer.current) clearTimeout(toastTimer.current);
    toastTimer.current = setTimeout(() => setShowToast(false), TOAST_MS);
    onDownload?.(invoiceId);
  };
  const handleShare = () => (onShare ? onShare(invoiceId) : Alert.alert('Share', `Sharing ${invoiceId}...`));

  const infoRows = [
    [
      { label: 'Invoice Number', value: record.invoiceId },
      { label: 'Order Number', value: record.orderNumber },
    ],
    [
      { label: 'Date', value: record.date },
      { label: 'Sales Channel', value: record.salesChannel },
    ],
    [
      { label: 'Invoice Type', value: record.invoiceType },
      { label: 'Status', value: record.status },
    ],
    [
      { label: 'Warehouse', value: record.warehouseName ?? record.warehouseId ?? '—' },
      ...(record.downloadAvailable !== undefined
        ? [{ label: 'Download Availability', value: record.downloadAvailable ? 'Available' : 'Unavailable' }]
        : []),
    ],
  ];

  const timeline = [
    record.generatedAt ? { title: 'Invoice Generated', time: record.generatedAt } : null,
    record.linkedAt ? { title: 'Invoice Linked to Order', time: record.linkedAt } : null,
  ].filter((step): step is { title: string; time: string } => step !== null);

  return (
    <BillingScreen
      title="Invoice Detail"
      subtitle={`${record.invoiceId} · ${record.status}`}
      onBack={onBack}
      headerRight={
        canView ? (
          <HeaderIconButton onPress={handleDownload} accessibilityLabel="Download Invoice">
            <DownloadIcon />
          </HeaderIconButton>
        ) : null
      }
      footer={
        canView ? (
          <BillingFooter>
            {showToast ? <BillingToast message="Invoice downloaded" /> : null}
            <BillingButton label="Download Invoice" icon={<DownloadIcon />} onPress={handleDownload} />
            <BillingButton label="Share" variant="outline" onPress={handleShare} />
          </BillingFooter>
        ) : null
      }
    >
      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        <View style={styles.brandBlock}>
          <Text style={styles.brandTitle}>TOHFA</Text>
          <Text style={styles.brandSubtitle}>Nilgiris Horticulture Organic Farmers Association</Text>
          <View style={styles.brandDivider} />
          <Text style={styles.invoiceDocLabel}>Invoice · {record.invoiceId}</Text>
        </View>

        <SectionTitle>Invoice Information</SectionTitle>
        <InfoCard rows={infoRows} />

        <SectionTitle>Bill To</SectionTitle>
        <Card>
          <Text style={styles.billToName}>{record.customerName}</Text>
          <Text style={styles.billToDetails}>
            Customer ID: {record.customerId} · Mobile: {record.customerPhone}
          </Text>
        </Card>

        <SectionTitle>Product / Line Items</SectionTitle>
        <Card>
          {record.items.map((item, index) => (
            <View key={`${item.name}-${index}`}>
              {index > 0 ? <View style={styles.divider} /> : null}
              <View style={styles.itemRow}>
                <View style={styles.itemLeft}>
                  <Text style={styles.itemName}>{item.name}</Text>
                  <Text style={styles.itemMeta}>
                    {item.grade} · {item.unit}
                  </Text>
                  <Text style={styles.itemMeta}>
                    {item.quantity} × {item.unitPrice}
                  </Text>
                </View>
                <Text style={styles.itemPrice}>{item.lineTotal}</Text>
              </View>
            </View>
          ))}
        </Card>

        <SectionTitle>Amount Summary</SectionTitle>
        <Card>
          {[
            ['Subtotal', record.subtotal],
            ['Discount', record.discount],
            ['GST', record.gst],
          ].map(([label, value]) => (
            <View key={label} style={styles.summaryRow}>
              <Text style={styles.summaryLabel}>{label}</Text>
              <Text style={styles.summaryValue}>{value}</Text>
            </View>
          ))}
          <View style={styles.divider} />
          <View style={styles.summaryRow}>
            <Text style={styles.totalLabel}>Total</Text>
            <Text style={styles.totalValue}>{record.total}</Text>
          </View>
        </Card>

        <SectionTitle>Payment Information</SectionTitle>
        <InfoCard
          rows={[
            [
              { label: 'Payment Status', value: record.paymentStatus },
              { label: 'Payment Method', value: record.paymentMethod },
            ],
          ]}
        />

        {timeline.length > 0 ? (
          <>
            <SectionTitle>Invoice Timeline</SectionTitle>
            <Card>
              {timeline.map((step, index) => (
                <View key={step.title} style={styles.timelineStep}>
                  <View style={styles.timelineIconCol}>
                    <TimelineCheckIcon />
                    {index < timeline.length - 1 ? <View style={styles.timelineLine} /> : null}
                  </View>
                  <View style={styles.timelineContent}>
                    <Text style={styles.timelineTitle}>{step.title}</Text>
                    <Text style={styles.timelineTime}>{step.time}</Text>
                  </View>
                </View>
              ))}
            </Card>
          </>
        ) : null}

        {record.generatedBy ? (
          <View style={styles.generatedBy}>
            <InfoCard rows={[[{ label: 'Generated By', value: record.generatedBy }]]} />
          </View>
        ) : null}

        {isAllWarehouses(scope) ? (
          <>
            <InfoNote>
              This customer-facing invoice never exposes farmer name, farm location, village, GPS, or internal listing
              ID.
            </InfoNote>
            {canView ? (
              <InfoNote>Signed download links expire after 5 minutes — no permanent public invoice URL.</InfoNote>
            ) : null}
          </>
        ) : null}
      </ScrollView>
    </BillingScreen>
  );
}

const TIMELINE_LINE_HEIGHT = 28;

const styles = StyleSheet.create({
  scrollContent: { paddingHorizontal: adminSpacing.lg, paddingTop: adminSpacing.md, paddingBottom: adminSpacing.xl },
  brandBlock: { alignItems: 'center', paddingVertical: adminSpacing.md },
  brandTitle: { ...adminType.title, color: adminColors.brand },
  brandSubtitle: { ...adminType.rowMeta, color: adminColors.muted, marginTop: 2, textAlign: 'center' },
  brandDivider: {
    alignSelf: 'stretch',
    height: 1,
    backgroundColor: adminColors.border,
    marginVertical: adminSpacing.sm,
  },
  invoiceDocLabel: { ...adminType.sectionHead, color: adminColors.ink },

  billToName: { ...adminType.rowTitle, color: adminColors.ink },
  billToDetails: { ...adminType.rowMeta, color: adminColors.muted, marginTop: 2 },

  divider: { height: 1, backgroundColor: adminColors.border, marginVertical: adminSpacing.sm },
  itemRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' },
  itemLeft: { flex: 1 },
  itemName: { ...adminType.rowTitle, color: adminColors.ink },
  itemMeta: { ...adminType.rowMeta, color: adminColors.muted, marginTop: 1 },
  itemPrice: { ...adminType.sectionHead, color: adminColors.ink },

  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: adminSpacing.xs,
  },
  summaryLabel: { ...adminType.body, color: adminColors.muted },
  summaryValue: { ...adminType.rowTitle, color: adminColors.ink },
  totalLabel: { ...adminType.sectionHead, color: adminColors.ink },
  totalValue: { ...adminType.kpiValue, color: adminColors.ink },

  timelineStep: { flexDirection: 'row', alignItems: 'flex-start' },
  timelineIconCol: { alignItems: 'center', width: adminSpacing.xl },
  timelineLine: { width: 2, height: TIMELINE_LINE_HEIGHT, backgroundColor: adminColors.border, marginVertical: 2 },
  timelineContent: { flex: 1, marginLeft: adminSpacing.sm, paddingBottom: adminSpacing.md },
  timelineTitle: { ...adminType.rowTitle, color: adminColors.ink },
  timelineTime: { ...adminType.rowMeta, color: adminColors.muted, marginTop: 2 },

  generatedBy: { marginTop: adminSpacing.md, borderRadius: adminRadius.lg },
});
