/**
 * name -> Private Use Area codepoint, for every Material Symbols Outlined
 * glyph this app actually references (see Icon.tsx for why codepoints, not
 * ligature-name text, is how this has to be rendered).
 *
 * This list was generated by extracting the `cmap` table of the shipped
 * `material-symbols` font (weight 400, fill 0, grade 0, optical size 24 —
 * its default static instance) and keeping only the entries this codebase's
 * `<Icon name="...">` and `iconName="..."` call sites use, then subsetting
 * the .ttf asset (apps/mobile/src/assets/fonts/MaterialSymbolsOutlined.ttf)
 * down to just those glyphs. Do not add names here that aren't referenced
 * anywhere in the app — add the glyph to the font subset too if you do
 * (see the icon-font regeneration note in Icon.tsx).
 */
export const ICON_CODEPOINTS: Readonly<Record<string, number>> = {
  account_balance_wallet: 0xe850,
  add: 0xe145,
  admin_panel_settings: 0xef3d,
  air: 0xefd8,
  arrow_back: 0xe5c4,
  arrow_downward: 0xe5db,
  arrow_upward: 0xe5d8,
  assignment: 0xe85d,
  badge: 0xea67,
  block: 0xf08c,
  calendar_month: 0xebcc,
  calendar_today: 0xe935,
  call: 0xf0d4,
  cancel: 0xe888,
  check: 0xe668,
  check_circle: 0xf0be,
  chevron_right: 0xe5cc,
  circle: 0xef4a,
  close: 0xe5cd,
  credit_card: 0xe8a1,
  crop_free: 0xe3c2,
  delete: 0xe92e,
  description: 0xe873,
  download: 0xf090,
  eco: 0xea35,
  edit: 0xf097,
  edit_note: 0xe745,
  error: 0xf8b6,
  expand_more: 0xe5cf,
  folder: 0xe2c7,
  groups: 0xf233,
  help: 0xe8fd,
  home: 0xe9b2,
  inbox: 0xe156,
  info: 0xe88e,
  inventory_2: 0xe1a1,
  lightbulb: 0xe90f,
  lock: 0xe899,
  mark_email_read: 0xf18c,
  menu_book: 0xea19,
  military_tech: 0xea3f,
  notifications: 0xe7f5,
  nutrition: 0xe110,
  palette: 0xe40a,
  park: 0xea63,
  person: 0xf0d3,
  place: 0xf1db,
  rainy: 0xf176,
  save: 0xe161,
  schedule: 0xefd6,
  science: 0xea4b,
  search: 0xef7a,
  settings: 0xe8b8,
  share: 0xe80d,
  shield: 0xe9e0,
  shopping_cart: 0xe8cc,
  star: 0xf09a,
  storefront: 0xea12,
  swap_horiz: 0xe8d4,
  trending_up: 0xe8e5,
  undo: 0xe166,
  upload: 0xf09b,
  verified: 0xef76,
  verified_user: 0xf013,
  visibility: 0xe8f4,
  visibility_off: 0xe8f5,
  warning: 0xf083,
  water_drop: 0xe798,
  wb_sunny: 0xe430,
  wifi_off: 0xe648,
};

/**
 * Names used in this codebase that Material Symbols does not ship under
 * that exact name, mapped to the glyph that *is* in the font, where that
 * mapping is an unambiguous, documented rename rather than a guess:
 *
 * - `error_outline` was a Material Icons name. Material Symbols merged the
 *   filled/outlined distinction into the `FILL` variable-font axis, so the
 *   single `error` glyph in the Outlined family IS the outline glyph
 *   `error_outline` used to point to — this is not a different icon.
 *
 * Deliberately NOT aliased here (no unambiguous replacement found in the
 * current Material Symbols catalog — see Icon.tsx's fallback behavior and
 * the bug-fix report for these two):
 * - `gps_fixed` (used in Step3Location.tsx, FieldContextScreen.tsx,
 *   FMBSketchScreen.tsx)
 * - `terrain` (used in ProfileScreen.tsx, ZonesScreen.tsx, AddZoneScreen.tsx)
 */
export const ICON_ALIASES: Readonly<Record<string, string>> = {
  error_outline: 'error',
};
