import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  SafeAreaView,
  StatusBar,
  Alert,
} from 'react-native';
import Svg, { Path, Circle, Rect, Polyline } from 'react-native-svg';

const PALETTE = {
  primary: '#F0562A',
  pageBg: '#F7F5EE',
  cardBg: '#FFFFFF',
  textInk: '#1D2420',
  textSecondary: '#7A726C',
  border: '#E8E4D9',
  greenDot: '#1E8E5A',
};

function ArrowBackIcon({ size = 24, color = '#FFFFFF' }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path d="M19 12H5M12 19l-7-7 7-7" stroke={color} strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

function DownloadIcon({ size = 18, color = '#F0562A' }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path
        d="M12 3v12m0 0l-4-4m4 4l4-4M4 17v2a2 2 0 002 2h12a2 2 0 002-2v-2"
        stroke={color}
        strokeWidth="2.2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </Svg>
  );
}

function CheckCircleDot({ size = 18, color = '#1E8E5A' }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Circle cx="12" cy="12" r="8" stroke={color} strokeWidth="2" />
      <Circle cx="12" cy="12" r="3" fill={color} />
    </Svg>
  );
}

export interface SubWarehouseInvoiceHistoryDetailScreenProps {
  invoiceId?: string;
  onBack?: () => void;
  onDownload?: () => void;
}

export function SubWarehouseInvoiceHistoryDetailScreen({
  invoiceId = 'INV-2026-001245',
  onBack,
  onDownload,
}: SubWarehouseInvoiceHistoryDetailScreenProps): React.JSX.Element {
  return (
    <SafeAreaView style={styles.root}>
      <StatusBar barStyle="light-content" backgroundColor="#D97706" />
      
      {/* ─── Header ─── */}
      <View style={styles.header}>
        <TouchableOpacity style={styles.backButton} onPress={onBack} activeOpacity={0.7}>
          <ArrowBackIcon size={22} color="#FFFFFF" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Invoice History Detail</Text>
      </View>

      <ScrollView style={styles.scroll} contentContainerStyle={styles.scrollContent}>
        {/* ─── Info Card ─── */}
        <View style={styles.card}>
          <View style={styles.row}>
            <View style={styles.col}>
              <Text style={styles.label}>Invoice Number</Text>
              <Text style={styles.val}>{invoiceId}</Text>
            </View>
            <View style={styles.col}>
              <Text style={styles.label}>Source Order/Sale</Text>
              <Text style={styles.val}>ORD-002154</Text>
            </View>
          </View>
          
          <View style={styles.row}>
            <View style={styles.col}>
              <Text style={styles.label}>Customer</Text>
              <Text style={styles.val}>Ravi Kumar</Text>
            </View>
            <View style={styles.col}>
              <Text style={styles.label}>Invoice Type</Text>
              <Text style={styles.val}>Retail Sale</Text>
            </View>
          </View>

          <View style={styles.row}>
            <View style={styles.col}>
              <Text style={styles.label}>Amount</Text>
              <Text style={styles.val}>₹2,450</Text>
            </View>
            <View style={styles.col}>
              <Text style={styles.label}>Generated Date/Time</Text>
              <Text style={styles.val}>25 Sep, 10:42 AM</Text>
            </View>
          </View>

          <View style={styles.row}>
            <View style={styles.col}>
              <Text style={styles.label}>Generated By</Text>
              <Text style={styles.val}>SWA - Suresh</Text>
            </View>
            <View style={styles.col}>
              <Text style={styles.label}>Warehouse</Text>
              <Text style={styles.val}>Coonoor</Text>
            </View>
          </View>

          <View style={styles.row}>
            <View style={styles.col}>
              <Text style={styles.label}>Status</Text>
              <Text style={styles.val}>Generated</Text>
            </View>
            <View style={styles.col}>
              <Text style={styles.label}>Download Availability</Text>
              <Text style={styles.val}>Available</Text>
            </View>
          </View>
        </View>

        {/* ─── Timeline ─── */}
        <Text style={styles.sectionTitle}>Timeline</Text>
        
        <View style={styles.timelineItem}>
          <View style={styles.timelineIconContainer}>
            <CheckCircleDot />
            <View style={styles.timelineLine} />
          </View>
          <View style={styles.timelineContent}>
            <Text style={styles.timelineTitle}>Invoice Generated</Text>
            <Text style={styles.timelineTime}>10:42 AM</Text>
          </View>
        </View>

        <View style={styles.timelineItem}>
          <View style={styles.timelineIconContainer}>
            <CheckCircleDot />
            <View style={[styles.timelineLine, { backgroundColor: 'transparent' }]} />
          </View>
          <View style={styles.timelineContent}>
            <Text style={styles.timelineTitle}>Invoice Linked to Order</Text>
            <Text style={styles.timelineTime}>10:42 AM</Text>
          </View>
        </View>

        <TouchableOpacity 
          style={styles.downloadOutlineBtn}
          onPress={onDownload ? onDownload : () => Alert.alert('Download', 'Downloading PDF...')}
        >
          <DownloadIcon color="#D97706" />
          <Text style={styles.downloadOutlineBtnText}>Download Invoice</Text>
        </TouchableOpacity>

      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: PALETTE.pageBg },
  header: {
    backgroundColor: '#D97706',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
  },
  backButton: { paddingRight: 16 },
  headerTitle: { fontFamily: 'Poppins', fontSize: 18, fontWeight: '700', color: '#FFFFFF' },
  scroll: { flex: 1 },
  scrollContent: { padding: 16 },
  card: {
    backgroundColor: PALETTE.cardBg,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: PALETTE.border,
    marginBottom: 24,
    gap: 16,
  },
  row: { flexDirection: 'row' },
  col: { flex: 1 },
  label: { fontFamily: 'Poppins', fontSize: 11, color: PALETTE.textSecondary, marginBottom: 4 },
  val: { fontFamily: 'Poppins', fontSize: 13, fontWeight: '600', color: PALETTE.textInk },
  sectionTitle: { fontFamily: 'Poppins', fontSize: 15, fontWeight: '700', color: PALETTE.textInk, marginBottom: 16 },
  timelineItem: { flexDirection: 'row', marginBottom: 0 },
  timelineIconContainer: { alignItems: 'center', width: 24, marginRight: 12 },
  timelineLine: { width: 1, flex: 1, backgroundColor: PALETTE.border, marginVertical: 4 },
  timelineContent: { paddingBottom: 24, flex: 1, justifyContent: 'flex-start', paddingTop: 0 },
  timelineTitle: { fontFamily: 'Poppins', fontSize: 13, fontWeight: '700', color: PALETTE.textInk },
  timelineTime: { fontFamily: 'Poppins', fontSize: 11, color: PALETTE.textSecondary, marginTop: 2 },
  downloadOutlineBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#D97706',
    borderRadius: 8,
    height: 48,
    marginTop: 16,
    gap: 8,
    backgroundColor: '#FFFFFF',
  },
  downloadOutlineBtnText: {
    fontFamily: 'Poppins',
    fontSize: 14,
    fontWeight: '700',
    color: '#D97706',
  },
});
