import React, { useState } from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
  Alert,
} from 'react-native';
import Svg, { Circle, Path, Rect } from 'react-native-svg';

// ─── Design Tokens (#F0562A Primary Brand Palette) ───────────────────────────
const PALETTE = {
  primary: '#F0562A',
  pageBg: '#FAF7F2',
  cardBg: '#FFFFFF',
  textInk: '#1E1612',
  textSecondary: '#7A726C',
  border: '#EBE5DC',
  divider: '#F4EFE9',
  greenSuccessBg: '#E8F5E9',
  greenSuccess: '#1E8E5A',
  blueBoxBg: '#EFF6FF',
  blueBoxBorder: '#BFDBFE',
  blueBoxText: '#1E40AF',
  secondaryBtnBorder: '#E09267',
  secondaryBtnText: '#9A4C1C',
};

// ─── Icons ───────────────────────────────────────────────────────────────────
function ArrowBackIcon({ size = 22, color = '#FFFFFF' }: { size?: number; color?: string }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path
        d="M19 12H5M12 19l-7-7 7-7"
        stroke={color}
        strokeWidth="2.4"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </Svg>
  );
}

function DocumentIcon({ size = 20, color = '#FFFFFF' }: { size?: number; color?: string }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path
        d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6z"
        stroke={color}
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <Path d="M14 2v6h6M16 13H8M16 17H8M10 9H8" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
    </Svg>
  );
}

function HashTagIcon({ size = 16, color = PALETTE.blueBoxText }: { size?: number; color?: string }) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Path
        d="M4 9h16M4 15h16M10 3L8 21M16 3l-2 18"
        stroke={color}
        strokeWidth="2.2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </Svg>
  );
}

export interface SubWarehouseInvoiceGeneratedScreenProps {
  invoiceId?: string;
  onBack?: () => void;
  onViewInvoice?: (invoiceId: string) => void;
  onDownload?: () => void;
}

export function SubWarehouseInvoiceGeneratedScreen({
  invoiceId = 'INV-2026-001245',
  onBack,
  onViewInvoice,
  onDownload,
}: SubWarehouseInvoiceGeneratedScreenProps): React.JSX.Element {
  const [downloaded, setDownloaded] = useState(false);

  const handleDownload = () => {
    setDownloaded(true);
    if (onDownload) {
      onDownload();
    } else {
      Alert.alert('Invoice Downloaded', `Invoice ${invoiceId} has been downloaded to device storage.`);
    }
  };

  return (
    <SafeAreaView style={styles.safeArea}>
      <StatusBar barStyle="light-content" backgroundColor={PALETTE.primary} />

      {/* ─── Header ─── */}
      <View style={styles.header}>
        <View style={styles.headerRow}>
          <TouchableOpacity
            style={styles.backButton}
            onPress={onBack}
            activeOpacity={0.8}
            hitSlop={{ top: 12, bottom: 12, left: 12, right: 12 }}
          >
            <ArrowBackIcon size={24} color="#FFFFFF" />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>Invoice Generated</Text>
        </View>
      </View>

      {/* ─── Body ─── */}
      <ScrollView
        style={styles.content}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        {/* Success Icon Circle */}
        <View style={styles.successIconWrapper}>
          <View style={styles.successIconCircle}>
            <Svg width={36} height={36} viewBox="0 0 24 24" fill="none">
              <Circle cx="12" cy="12" r="10" stroke={PALETTE.greenSuccess} strokeWidth="2.2" />
              <Path
                d="M8 12l2.5 2.5 5.5-5.5"
                stroke={PALETTE.greenSuccess}
                strokeWidth="2.4"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </Svg>
          </View>
        </View>

        {/* Title */}
        <Text style={styles.titleText}>Invoice Generated</Text>

        {/* Invoice Number Card */}
        <View style={styles.card}>
          <Text style={styles.invoiceNumberLabel}>Invoice Number</Text>
          <Text style={styles.invoiceNumberValue}>{invoiceId}</Text>
        </View>

        {/* Info Box */}
        <View style={styles.infoBox}>
          <View style={styles.infoIconCol}>
            <HashTagIcon size={18} />
          </View>
          <Text style={styles.infoText}>
            This number is generated by the backend under a sequence/lock — never counted or assigned on the client.
          </Text>
        </View>
      </ScrollView>

      {/* ─── Bottom Buttons ─── */}
      <View style={styles.bottomBar}>
        <TouchableOpacity
          style={styles.viewInvoiceBtn}
          onPress={() => {
            if (onViewInvoice) {
              onViewInvoice(invoiceId);
            } else if (onBack) {
              onBack();
            }
          }}
          activeOpacity={0.88}
        >
          <DocumentIcon size={20} color="#FFFFFF" />
          <Text style={styles.viewInvoiceText}>View Invoice</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.downloadBtn}
          onPress={handleDownload}
          activeOpacity={0.88}
        >
          <Text style={styles.downloadBtnText}>
            {downloaded ? 'Downloaded' : 'Download'}
          </Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: PALETTE.primary,
  },
  header: {
    backgroundColor: PALETTE.primary,
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.2,
  },
  content: {
    flex: 1,
    backgroundColor: PALETTE.pageBg,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 36,
    paddingBottom: 32,
    alignItems: 'center',
  },
  successIconWrapper: {
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successIconCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: PALETTE.greenSuccessBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleText: {
    fontSize: 22,
    fontWeight: '800',
    color: PALETTE.textInk,
    marginBottom: 24,
    textAlign: 'center',
  },
  card: {
    width: '100%',
    backgroundColor: PALETTE.cardBg,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: PALETTE.border,
    padding: 16,
    marginBottom: 14,
  },
  invoiceNumberLabel: {
    fontSize: 13,
    color: PALETTE.textSecondary,
    marginBottom: 6,
    fontWeight: '500',
  },
  invoiceNumberValue: {
    fontSize: 17,
    fontWeight: '800',
    color: PALETTE.textInk,
    letterSpacing: 0.2,
  },
  infoBox: {
    width: '100%',
    flexDirection: 'row',
    backgroundColor: PALETTE.blueBoxBg,
    borderWidth: 1,
    borderColor: PALETTE.blueBoxBorder,
    borderRadius: 14,
    padding: 14,
    gap: 10,
    alignItems: 'flex-start',
  },
  infoIconCol: {
    marginTop: 2,
  },
  infoText: {
    flex: 1,
    fontSize: 12.5,
    color: PALETTE.blueBoxText,
    lineHeight: 18,
    fontWeight: '500',
  },
  bottomBar: {
    backgroundColor: PALETTE.cardBg,
    borderTopWidth: 1,
    borderTopColor: PALETTE.divider,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    gap: 12,
  },
  viewInvoiceBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: PALETTE.primary,
    borderRadius: 12,
    paddingVertical: 14,
    gap: 8,
  },
  viewInvoiceText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  downloadBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: PALETTE.secondaryBtnBorder,
    paddingVertical: 14,
  },
  downloadBtnText: {
    fontSize: 16,
    fontWeight: '800',
    color: PALETTE.secondaryBtnText,
  },
});
