#!/usr/bin/env tsx
/**
 * Generates apps/mobile/src/roles/admin/permissions/demoGrants.ts from
 * docs/rbac.json — `pnpm gen:demo-grants`.
 *
 * The module is a DEV-ONLY stand-in for GET /auth/me while the mobile demo
 * admin login has not produced a token (see warehousePermissions.ts). It lists,
 * per warehouse role, exactly the codes the server itself would return: the
 * grants whose scope is not 'none' (apps/api auth.repo getUserPermissions).
 *
 * Re-run after editing docs/rbac.json. The vitest
 * apps/mobile/src/roles/admin/tests/warehousePermissions.test.ts recomputes the
 * lists from rbac.json and fails if the committed module has drifted.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const RBAC_PATH = join(REPO_ROOT, 'docs', 'rbac.json');
const OUT_PATH = join(REPO_ROOT, 'apps', 'mobile', 'src', 'roles', 'admin', 'permissions', 'demoGrants.ts');

const ROLES = ['SUB_WH_ADMIN', 'MAIN_WH_ADMIN'] as const;

interface RbacFile {
  version: string;
  permissions: Array<{ code: string; grants: Record<string, string> }>;
}

const rbac = JSON.parse(readFileSync(RBAC_PATH, 'utf8')) as RbacFile;

const lines: string[] = [];
lines.push('// GENERATED by scripts/gen-demo-grants.ts from docs/rbac.json — do not edit by hand.');
lines.push('// Regenerate with `pnpm gen:demo-grants`; the drift test in');
lines.push('// roles/admin/tests/warehousePermissions.test.ts fails when this is stale.');
lines.push('//');
lines.push('// DEV-ONLY demo stand-in for GET /auth/me (see ./warehousePermissions.ts). It');
lines.push("// grants nothing: the server still authorises every call on the caller's token.");
lines.push('');
lines.push("export type DemoWarehouseRole = 'SUB_WH_ADMIN' | 'MAIN_WH_ADMIN';");
lines.push('');
lines.push('export const DEMO_ROLE_PERMISSIONS: Readonly<Record<DemoWarehouseRole, readonly string[]>> = {');
for (const role of ROLES) {
  const codes = rbac.permissions
    .filter((p) => (p.grants[role] ?? 'none') !== 'none')
    .map((p) => p.code)
    .sort();
  lines.push(`  ${role}: [`);
  for (const code of codes) lines.push(`    '${code}',`);
  lines.push('  ],');
}
lines.push('};');
lines.push('');

writeFileSync(OUT_PATH, lines.join('\n'));
console.log(`wrote ${OUT_PATH}`);
